import type { Security } from '@/types/security'

// ─── Security Master Seed (Phase 0C) ───────────────────────────────────────────
//
// Data only — no logic. The union of every symbol the app already references
// (mock holdings, movers, benchmark, default recent symbols, command-palette
// symbols), plus a couple of indices to exercise the non-tradable case and the
// deliberate cross-listing collisions (RY, TD) that make ambiguity meaningful.
//
// `securityId` is authored by hand using the readable convention
// `${country}:${symbol}`, but it is an OPAQUE, FROZEN key: runtime code never
// recomputes it. U.S.-listed Canadian names (RY, TD) are seeded as COMMON_STOCK,
// NOT ADR, because their ADR/ordinary status is not verified here.

/** Fixed verification timestamp for seed records. */
export const SEED_VERIFIED_AT = '2026-06-04T00:00:00.000Z'

export const SECURITY_MASTER_SEED: Security[] = [
  // ── U.S. equities (common stock) ──────────────────────────────────────────
  {
    securityId: 'US:AAPL',
    symbol: 'AAPL',
    displaySymbol: 'AAPL',
    name: 'Apple Inc.',
    assetClass: 'EQUITY',
    securityType: 'COMMON_STOCK',
    exchange: 'NASDAQ',
    currency: 'USD',
    country: 'US',
    sector: 'Technology',
    isActive: true,
    isTradable: true,
    dataSources: ['SEED'],
    lastVerified: SEED_VERIFIED_AT,
  },
  {
    securityId: 'US:MSFT',
    symbol: 'MSFT',
    displaySymbol: 'MSFT',
    name: 'Microsoft Corp.',
    assetClass: 'EQUITY',
    securityType: 'COMMON_STOCK',
    exchange: 'NASDAQ',
    currency: 'USD',
    country: 'US',
    sector: 'Technology',
    isActive: true,
    isTradable: true,
    dataSources: ['SEED'],
    lastVerified: SEED_VERIFIED_AT,
  },
  {
    securityId: 'US:GOOGL',
    symbol: 'GOOGL',
    displaySymbol: 'GOOGL',
    name: 'Alphabet Inc. (Class A)',
    assetClass: 'EQUITY',
    securityType: 'COMMON_STOCK',
    exchange: 'NASDAQ',
    currency: 'USD',
    country: 'US',
    sector: 'Communication Services',
    isActive: true,
    isTradable: true,
    dataSources: ['SEED'],
    lastVerified: SEED_VERIFIED_AT,
  },
  {
    securityId: 'US:NVDA',
    symbol: 'NVDA',
    displaySymbol: 'NVDA',
    name: 'NVIDIA Corp.',
    assetClass: 'EQUITY',
    securityType: 'COMMON_STOCK',
    exchange: 'NASDAQ',
    currency: 'USD',
    country: 'US',
    sector: 'Technology',
    isActive: true,
    isTradable: true,
    dataSources: ['SEED'],
    lastVerified: SEED_VERIFIED_AT,
  },
  {
    securityId: 'US:AMD',
    symbol: 'AMD',
    displaySymbol: 'AMD',
    name: 'Advanced Micro Devices, Inc.',
    assetClass: 'EQUITY',
    securityType: 'COMMON_STOCK',
    exchange: 'NASDAQ',
    currency: 'USD',
    country: 'US',
    sector: 'Technology',
    isActive: true,
    isTradable: true,
    dataSources: ['SEED'],
    lastVerified: SEED_VERIFIED_AT,
  },
  {
    securityId: 'US:META',
    symbol: 'META',
    displaySymbol: 'META',
    name: 'Meta Platforms, Inc.',
    assetClass: 'EQUITY',
    securityType: 'COMMON_STOCK',
    exchange: 'NASDAQ',
    currency: 'USD',
    country: 'US',
    sector: 'Communication Services',
    aliases: ['FB'],
    isActive: true,
    isTradable: true,
    dataSources: ['SEED'],
    lastVerified: SEED_VERIFIED_AT,
  },
  {
    securityId: 'US:TSLA',
    symbol: 'TSLA',
    displaySymbol: 'TSLA',
    name: 'Tesla, Inc.',
    assetClass: 'EQUITY',
    securityType: 'COMMON_STOCK',
    exchange: 'NASDAQ',
    currency: 'USD',
    country: 'US',
    sector: 'Consumer Discretionary',
    isActive: true,
    isTradable: true,
    dataSources: ['SEED'],
    lastVerified: SEED_VERIFIED_AT,
  },
  {
    securityId: 'US:INTC',
    symbol: 'INTC',
    displaySymbol: 'INTC',
    name: 'Intel Corp.',
    assetClass: 'EQUITY',
    securityType: 'COMMON_STOCK',
    exchange: 'NASDAQ',
    currency: 'USD',
    country: 'US',
    sector: 'Technology',
    isActive: true,
    isTradable: true,
    dataSources: ['SEED'],
    lastVerified: SEED_VERIFIED_AT,
  },
  {
    securityId: 'US:PFE',
    symbol: 'PFE',
    displaySymbol: 'PFE',
    name: 'Pfizer Inc.',
    assetClass: 'EQUITY',
    securityType: 'COMMON_STOCK',
    exchange: 'NYSE',
    currency: 'USD',
    country: 'US',
    sector: 'Health Care',
    isActive: true,
    isTradable: true,
    dataSources: ['SEED'],
    lastVerified: SEED_VERIFIED_AT,
  },
  {
    securityId: 'US:BA',
    symbol: 'BA',
    displaySymbol: 'BA',
    name: 'Boeing Co.',
    assetClass: 'EQUITY',
    securityType: 'COMMON_STOCK',
    exchange: 'NYSE',
    currency: 'USD',
    country: 'US',
    sector: 'Industrials',
    isActive: true,
    isTradable: true,
    dataSources: ['SEED'],
    lastVerified: SEED_VERIFIED_AT,
  },
  {
    securityId: 'US:RIO',
    symbol: 'RIO',
    displaySymbol: 'RIO',
    name: 'Rio Tinto Group',
    assetClass: 'EQUITY',
    // Listing is a depositary receipt in practice, but unverified here → COMMON_STOCK.
    securityType: 'COMMON_STOCK',
    exchange: 'NYSE',
    currency: 'USD',
    country: 'US',
    sector: 'Materials',
    isActive: true,
    isTradable: true,
    dataSources: ['SEED'],
    lastVerified: SEED_VERIFIED_AT,
  },
  {
    securityId: 'US:RY',
    symbol: 'RY',
    displaySymbol: 'RY',
    name: 'Royal Bank of Canada',
    assetClass: 'EQUITY',
    // U.S. listing of a Canadian issuer — NOT classified as ADR (unverified).
    securityType: 'COMMON_STOCK',
    exchange: 'NYSE',
    currency: 'USD',
    country: 'US',
    sector: 'Financials',
    isActive: true,
    isTradable: true,
    dataSources: ['SEED'],
    lastVerified: SEED_VERIFIED_AT,
  },
  {
    securityId: 'US:TD',
    symbol: 'TD',
    displaySymbol: 'TD',
    name: 'The Toronto-Dominion Bank',
    assetClass: 'EQUITY',
    securityType: 'COMMON_STOCK',
    exchange: 'NYSE',
    currency: 'USD',
    country: 'US',
    sector: 'Financials',
    isActive: true,
    isTradable: true,
    dataSources: ['SEED'],
    lastVerified: SEED_VERIFIED_AT,
  },

  // ── U.S. ETFs ─────────────────────────────────────────────────────────────
  {
    securityId: 'US:SPY',
    symbol: 'SPY',
    displaySymbol: 'SPY',
    name: 'SPDR S&P 500 ETF Trust',
    assetClass: 'ETF',
    securityType: 'ETF',
    exchange: 'NYSE_ARCA',
    currency: 'USD',
    country: 'US',
    sector: 'ETF',
    isActive: true,
    isTradable: true,
    dataSources: ['SEED'],
    lastVerified: SEED_VERIFIED_AT,
  },
  {
    securityId: 'US:QQQ',
    symbol: 'QQQ',
    displaySymbol: 'QQQ',
    name: 'Invesco QQQ Trust',
    assetClass: 'ETF',
    securityType: 'ETF',
    exchange: 'NASDAQ',
    currency: 'USD',
    country: 'US',
    sector: 'ETF',
    isActive: true,
    isTradable: true,
    dataSources: ['SEED'],
    lastVerified: SEED_VERIFIED_AT,
  },
  {
    securityId: 'US:IWM',
    symbol: 'IWM',
    displaySymbol: 'IWM',
    name: 'iShares Russell 2000 ETF',
    assetClass: 'ETF',
    securityType: 'ETF',
    exchange: 'NYSE_ARCA',
    currency: 'USD',
    country: 'US',
    sector: 'ETF',
    isActive: true,
    isTradable: true,
    dataSources: ['SEED'],
    lastVerified: SEED_VERIFIED_AT,
  },
  {
    securityId: 'US:GLD',
    symbol: 'GLD',
    displaySymbol: 'GLD',
    name: 'SPDR Gold Shares',
    assetClass: 'ETF',
    securityType: 'ETF',
    exchange: 'NYSE_ARCA',
    currency: 'USD',
    country: 'US',
    sector: 'ETF',
    isActive: true,
    isTradable: true,
    dataSources: ['SEED'],
    lastVerified: SEED_VERIFIED_AT,
  },
  {
    securityId: 'US:TLT',
    symbol: 'TLT',
    displaySymbol: 'TLT',
    name: 'iShares 20+ Year Treasury Bond ETF',
    assetClass: 'ETF',
    securityType: 'ETF',
    exchange: 'NASDAQ',
    currency: 'USD',
    country: 'US',
    sector: 'ETF',
    isActive: true,
    isTradable: true,
    dataSources: ['SEED'],
    lastVerified: SEED_VERIFIED_AT,
  },

  // ── U.S. indices (active but NOT tradable) ────────────────────────────────
  {
    securityId: 'US:SPX',
    symbol: 'SPX',
    displaySymbol: 'SPX',
    name: 'S&P 500 Index',
    assetClass: 'INDEX',
    securityType: 'INDEX',
    exchange: 'INDEX',
    currency: 'USD',
    country: 'US',
    isActive: true,
    isTradable: false,
    dataSources: ['SEED'],
    lastVerified: SEED_VERIFIED_AT,
  },
  {
    securityId: 'US:NDX',
    symbol: 'NDX',
    displaySymbol: 'NDX',
    name: 'NASDAQ 100 Index',
    assetClass: 'INDEX',
    securityType: 'INDEX',
    exchange: 'INDEX',
    currency: 'USD',
    country: 'US',
    isActive: true,
    isTradable: false,
    dataSources: ['SEED'],
    lastVerified: SEED_VERIFIED_AT,
  },

  // ── Canadian listings (TSX) ───────────────────────────────────────────────
  {
    securityId: 'CA:RY.TO',
    symbol: 'RY.TO',
    displaySymbol: 'RY.TO',
    name: 'Royal Bank of Canada',
    assetClass: 'EQUITY',
    securityType: 'COMMON_STOCK',
    exchange: 'TSX',
    currency: 'CAD',
    country: 'CA',
    sector: 'Financials',
    isActive: true,
    isTradable: true,
    dataSources: ['SEED'],
    lastVerified: SEED_VERIFIED_AT,
  },
  {
    securityId: 'CA:TD.TO',
    symbol: 'TD.TO',
    displaySymbol: 'TD.TO',
    name: 'The Toronto-Dominion Bank',
    assetClass: 'EQUITY',
    securityType: 'COMMON_STOCK',
    exchange: 'TSX',
    currency: 'CAD',
    country: 'CA',
    sector: 'Financials',
    isActive: true,
    isTradable: true,
    dataSources: ['SEED'],
    lastVerified: SEED_VERIFIED_AT,
  },
  {
    securityId: 'CA:ENB.TO',
    symbol: 'ENB.TO',
    displaySymbol: 'ENB.TO',
    name: 'Enbridge Inc.',
    assetClass: 'EQUITY',
    securityType: 'COMMON_STOCK',
    exchange: 'TSX',
    currency: 'CAD',
    country: 'CA',
    sector: 'Energy',
    isActive: true,
    isTradable: true,
    dataSources: ['SEED'],
    lastVerified: SEED_VERIFIED_AT,
  },
  {
    securityId: 'CA:SU.TO',
    symbol: 'SU.TO',
    displaySymbol: 'SU.TO',
    name: 'Suncor Energy Inc.',
    assetClass: 'EQUITY',
    securityType: 'COMMON_STOCK',
    exchange: 'TSX',
    currency: 'CAD',
    country: 'CA',
    sector: 'Energy',
    isActive: true,
    isTradable: true,
    dataSources: ['SEED'],
    lastVerified: SEED_VERIFIED_AT,
  },
  {
    securityId: 'CA:SHOP.TO',
    symbol: 'SHOP.TO',
    displaySymbol: 'SHOP.TO',
    name: 'Shopify Inc.',
    assetClass: 'EQUITY',
    securityType: 'COMMON_STOCK',
    exchange: 'TSX',
    currency: 'CAD',
    country: 'CA',
    sector: 'Technology',
    isActive: true,
    isTradable: true,
    dataSources: ['SEED'],
    lastVerified: SEED_VERIFIED_AT,
  },
  {
    securityId: 'CA:XIU.TO',
    symbol: 'XIU.TO',
    displaySymbol: 'XIU.TO',
    name: 'iShares S&P/TSX 60 Index ETF',
    assetClass: 'ETF',
    securityType: 'ETF',
    exchange: 'TSX',
    currency: 'CAD',
    country: 'CA',
    sector: 'ETF',
    isActive: true,
    isTradable: true,
    dataSources: ['SEED'],
    lastVerified: SEED_VERIFIED_AT,
  },
]
